### ISSUE TITLE
Publish as NPM module

### ISSUE THREAD

**Issue by dontcallmedom** [tidoust/reffy#90] opened 2018-03-16 09:53 UTC
I've re-used some of the existing libraries in a number of small projects (in particular, the ability to extract and parse webidl from specs) - this would be made easier if reffy (or a subset of it?) was made available as an npm module

**Comment by tidoust** [comment] 2018-03-30 11:10
Closing this issue as Reffy is now available as an [npm package](http://npmjs.com/package/reffy).

v1.1.1 is the first version that runs correctly as an NPM package (a minor revision to add an `reffy.js` CLI to pilot Reffy as an installed module, followed by a patch revision to fix remaining path resolution error in spec list files). I wouldn't be surprised if something is still not running as intended when Reffy is used as an NPM module. Potential problems to be raised as separate issues...

**Closed by tidoust** 2018-03-30 11:10 UTC
